### ISSUE TITLE
import {Enum, EnumType, IStaticEnum} from "ts-jenum" doesn't work

### ISSUE THREAD

**Issue by voropa** [reforms/ts-jenum#1]
import {Enum, EnumType, IStaticEnum} from "ts-jenum" doesn't work for me.
[ts] Cannot find module 'ts-jenum';

Probably the problem is that there is no index.d.ts in the root of the module.

TypeScript v2.9.2
npm v6.1.0

**Comment by reforms** [comment]
Thank you. I found a couple of mistakes in package.json. I fixed it. Please, try again with 1.1.5 version of ts-jenum.

My steps to test:
 1. npm install ts-jenum (will download 1.1.5)
 2. look at package.json (there was a new section "dependencies": {
        "ts-jenum": "^1.1.5"
    })
 3. In some ts file: import {Enum, EnumType} from "ts-jenum" - work for me
